server:
  port: 9900
spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8000/realms/spring-microservices-security-realm
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: Product Service
        url: /aggregate/product-service/v3/api-docs
      - name: Order Service
        url: /aggregate/order-service/v3/api-docs
      - name: Inventory Service
        url: /aggregate/inventory-service/v3/api-docs
  api-docs:
    enabled: true
    path: /api-docs
# Actuator Endpoints
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
#Resilinece4j Properties
resilience4j:
  circuitbreaker:
    configs:
      default:
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        waitDurationInOpenState: 5s
#Resilience4J Timeout Properties
  timelimiter:
    configs:
      default:
        timeout-duration: 3s
  #Resilience4J Retry Properties
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 2s

#logging:
#  level:
#    org.springframework.security: DEBUG
#    org.springframework.security.oauth2: DEBUG

