server:
  port: 7002
spring:
  application:
    name: inventory-service
  datasource:
    url: 'jdbc:mysql://localhost:3307/inventory_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC'
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: none

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
